USE [spad_db]
GO
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (1, N'Antioquia', 05)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (2, N'Atlántico', 08)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (3, N'Bogotá, D.C.', 11)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (4, N'Bolívar', 13)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (5, N'Boyacá', 15)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (6, N'Caldas', 17)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (7, N'Caquetá', 18)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (8, N'Cauca', 19)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (9, N'Cesar', 20)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (10, N'Córdoba', 23)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (11, N'Cundinamarca', 25)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (12, N'Chocó', 27)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (13, N'Huila', 41)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (14, N'La Guajira', 44)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (15, N'Magdalena', 47)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (16, N'Meta', 50)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (17, N'Nariño', 52)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (18, N'Norte de Santander', 54)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (19, N'Quindio', 63)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (20, N'Risaralda', 66)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (21, N'Santander', 68)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (22, N'Sucre', 70)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (23, N'Tolima', 73)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (24, N'Valle del Cauca', 76)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (25, N'Arauca', 81)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (26, N'Casanare', 85)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (27, N'Putumayo', 86)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (28, N'Archipiélago de San Andrés, Providencia y Santa Catalina', 88)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (29, N'Amazonas', 91)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (30, N'Guainía', 94)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (31, N'Guaviare', 95)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (32, N'Vaupés', 97)
INSERT [dbo].[DepartamentoSet] ([IdDepartamento], [NombreDepartamento], [CodigoDivipola]) VALUES (33, N'Vichada', 99)
